name: compass
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.11
  - pip=24.2
  - tbb=2021.8.0
  - numba=0.59.1
  - numpy=1.26.4
  - pandas=2.2.2
  - mdtraj=1.9.9
  - importlib_metadata=7.1.0
  - biopython=1.84
  - rdkit=2023.09.6
  - pytest==8.3.3
  - setuptools=69.5.1
  - mdanalysis=2.7.0
  - prody=2.4.1
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - networkx=3.3
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - tqdm=4.66.5
  - ipython=8.27.0
  - ipympl=0.9.3
  - pip:
     - -e .  # install git checkout of compass in editable mode
     - numba-kdtree==0.4.0
     - jupyterlab==4.2.5
     - igraph==0.11.6
     - leidenalg==0.10.2
     - pytest==8.3.3
     - pytest-cov==5.0.0
     - tox==4.18.1
     - nbdime==4.0.2
     - nbstripout==0.7.1
     - sphinx==8.0.2
     - recommonmark==0.7.1
