name: compass
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python>=3.8
  - pip
  - tbb
  - numba~=0.59.1
  - numpy~=1.26.4
  - pandas~=2.2.2
  - mdtraj~=1.9.9
  - importlib_metadata~=7.1.0
  - biopython~=1.83
  - rdkit~=2023.9.3
  - pytest~=8.2.0
  - setuptools~=69.5.1
  - mdanalysis~=2.7.0
  - prody~=2.4.0
  - matplotlib~=3.8.4
  - seaborn~=0.13.2
  - networkx~=3.3
  - scikit-learn~=1.5.0
  - scipy
  - tqdm
  - ipython
  - ipympl
  - pip:
     - -e .  # install git checkout of compass in editable mode
     - numba-kdtree
     - jupyterlab
     - pytest
     - pytest-cov
     - tox
     - nbdime
     - nbstripout
     - sphinx
     - recommonmark
